%butterworth filter
clc;
close all;
ap = -3;
as = -40;
fp = 1000;
fs = 2000;
op = 2*pi*fp;
os = 2*pi*fs;
A = log10((10^(-ap/10)-1)/(10^(-as/10)-1));
B = 2*log10(op/os);
N = A/B;
N = ceil(N);
disp('Order of filter N = ');disp(N);
oc = os/((10^(-as/10-1)^(1/(2*N))));
disp('Cutoff freq, oc = ');
disp(oc);
[b,a] = butter(N,oc,'s');
fr  = 0:100:4000;
wr = 2*pi*fr;
[H,w] = freqs(b,a,wr);
f = w/(2*pi);
H_mag = 20*log10(abs(H));
figure;
plot(f,H_mag);
grid on;
xlabel('Frequency in Hz');
ylabel('Magnitude in dB');
title('Magnitude response');
Transferfunc = tf(b,a);
disp(Transferfunc);