%Chebyshev filter
clc;
close all;
ap = -3;
as = -40;
fp = 1000;
fs = 2000;
op = 2*pi*fp;
os = 2*pi*fs;
omegar = os/op;
epsilon = sqrt(10^(-ap/10)-1);
A = sqrt(10^(-as/10));
g = sqrt((A^2-1)/epsilon^2);
N = log10(g+sqrt(g^2-1))/log10(omegar+sqrt(omegar^2-1));
N = ceil(N);
disp('order of filter ');
disp(N);
[b,a] = cheby1(N,-ap,op,'s');
fr = 0:100:4000;
wr = 2*pi*fr;
[H,w] = freqs(b,a,wr);
f  = w/(2*pi);
H_mag = 20*log10(abs(H));
figure;
plot(f,H_mag);
grid on;
xlabel('frequency in Hz');
ylabel('magnitude in dB');
title('magnitude response');
Transferfunc = tf(b,a);
disp(Transferfunc);