%verification of sampling theorem
clc;
close all;
t = 0:0.001:0.2;
f1 = input('Enter input frequency = ');
f2 = input('Enter input frequency = ');
xa = cos(2*pi*f1*t) + cos(2*pi*f2*t);
fm = max(f1,f2);
fs = 2*fm;
ts = 1/fs;
n=0:1:(0.2*fs);
xd = cos(2*pi*f1*(n*ts)) + cos(2*pi*fs*(n*ts));
figure;
subplot(3,1,1);
plot(t,xa);
xlabel('t in s');
ylabel('amp');
title('Analog signal and Discrete signal');
hold on;
stem(n*ts,xd);
hold off;
legend('continuous xa(t)','xd(n)');
subplot(3,1,2);
stem(n,xd,'r');
xlabel('n samples');
ylabel('xd[n]');
title('Discrete Signal');
xr = xd*sinc((t-(n'*ts))/ts);
subplot(3,1,3);
plot(t,xr);
xlabel('t in s');
ylabel('xr(t)');
title('Right sampling');
